### ISSUE TITLE
Update the XHTML 1.1 RNG schema to latest version

### ISSUE THREAD

**Issue by tofi86** [IDPF/epubcheck#733]
Currently, as discussed in https://github.com/IDPF/epubcheck/issues/696#issuecomment-269758270, the XHTML 1.1 RNG schema in EpubCheck is outdated and/or manually edited.

The RNG schema needs to get updated to the latest XHTML 1.1 version. Also the `xhtml11-ent.dtd` probably needs an update.

- [x] update RNG schema
- [x] update `xhtml11-ent.dtd` (_not needed_)

**Comment by tofi86** [comment]
Updated the issue description above to reflect changes from comment https://github.com/IDPF/epubcheck/issues/696#issuecomment-269763683

Question: Where are the RNG XHTML 1.1 schemas from? Cannot find an official source?

/cc @rdeltour @mattgarrish

**Comment by tofi86** [comment]
> Also the xhtml11-ent.dtd probably needs an update.

The entities file is up to date with the [latest XHTML 1.1 DTD](https://www.w3.org/TR/xhtml11/DTD/xhtml11-flat.dtd). Just compared and checked that...

**Comment by tofi86** [comment]
**Tasks for _Update RNG schema_:** (https://www.w3.org/TR/xhtml-modularization/Overview.html#status)
- [x] **1. Changing the datatype of the `class` attribute** so that it permits an empty value
* Nothing to do here. The `class` attribute is already defined as `<ref name="Text.datatype"/>` which allows empty values.
* Added a test document anyways in 2cddb8b3
- [x] **2. Moving the name attribute for the form and img elements out of the legacy module and into their base modules**
* nothing to do here
- [x] **3. Changing the datatype for the `usemap` attribute** from `IDREF` to `URIREF`
* Fixed with 8629a02
