### ISSUE TITLE
Clean tests from OPF-058 and OPF-059 messages

### ISSUE THREAD

**Issue by tofi86** [IDPF/epubcheck#813]
`OPF-058` and `OPF-059` messages are scattered all along the tests in `src/test/resources/com/adobe/epubcheck/test/` and should be cleaned up by fixing the `toc.ncx` and `toc.xhtml` files in the particular tests. The messages appear because the guys from B&N/Nook built all theier tests on 'invalid' EPUBs. `OPF-058` and `OPF-059` are not explicitly checked in the tests and therefore have no place there.

Two new dedicated testcases for `OPF-058` and `OPF-059` need to be created based on our new minimal epub testdata in `src/test/resources/minimal-epub/` and a dedicated JUnit test needs to be set up.

I cleaned up a first batch of tests with commit 7d7365a8c9b93d7a86634fc99c6ab3a7c46a3b26 in PR #811 but didn't have the time to finish the rest of 40 other tests. You can identify them by looking at commit 11cb2452d8029bac7d31c136128902202e3a7fb2.

### Tasks
- [ ] Clean the tests
- [ ] Fix the *expected* JSON/XML files
- [ ] Create minimal epub tests
- [ ] Create JUnit tests for both new tests

**Comment by tofi86** [comment]
Of course this is low priority as those are only USAGE messages which aren't displayed by default.
